
# This file was *autogenerated* from the file get_seed.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4529255040439033800342855653030016000 = Integer(4529255040439033800342855653030016000); _sage_const_1 = Integer(1)
s = _sage_const_4529255040439033800342855653030016000 
seed = _sage_const_1 
for p, e in factor(s):
    seed *= pow(p, e) - pow(p, e-_sage_const_1 )

print(seed)

